# Generated by Django 6.0 on 2025-12-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0002_adoptante_animal_solicitud_delete_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='adoptante_nombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='animal_nombre',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdopcion.adoptante'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdopcion.animal'),
        ),
    ]
