# Generated by Django 6.0 on 2025-12-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0003_remove_solicitud_adoptante_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='adoptante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdopcion.adoptante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdopcion.animal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
