# Generated by Django 6.0 on 2025-12-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0004_animal_estado_alter_solicitud_adoptante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animales/'),
        ),
    ]
