# Generated by Django 6.0 on 2025-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0006_alter_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_de_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
    ]
