# Generated by Django 6.0 on 2025-12-25 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0008_adoptante_user_alter_adoptante_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='adoptante',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_de_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
