# Generated by Django 6.0 on 2025-12-23 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('especie', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='disponible', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animales/')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adoptante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
            ],
        ),
    ]
